version: '3.9'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd123456
      POSTGRES_DB: loyalty
    ports:
      - "5432:5432"
